name:                adventofcode-haskell
version:             0.1.0.0
github:              "heydtn/adventofcode-haskell"
license:             MIT
author:              "Nathaniel Heydt"
maintainer:          "heydtn"
copyright:           "2019 Nathaniel Heydt"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/heydtn/adventofcode-haskell#readme>

dependencies:
- base >= 4.7 && < 5
- wreq >= 0.5.3.2 && < 0.5.3.3
- process >= 1.6 && < 1.7
- directory >= 1.3 && < 1.4
- lens >= 4.18 && < 4.19
- http-client >= 0.6 && < 0.7
- time >= 1.8 && < 1.9
- bytestring >= 0.10.8 && < 0.10.9

library:
  source-dirs: src

executables:
  adventofcode-haskell-exe:
    main:                Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - adventofcode-haskell

default-extensions:
  ApplicativeDo
  BangPatterns
  ConstraintKinds
  DataKinds
  DefaultSignatures
  DeriveFoldable
  DeriveFunctor
  DeriveGeneric
  DeriveLift
  DeriveTraversable
  DerivingStrategies
  EmptyCase
  ExistentialQuantification
  FlexibleContexts
  FlexibleInstances
  FunctionalDependencies
  GADTs
  GeneralizedNewtypeDeriving
  InstanceSigs
  KindSignatures
  LambdaCase
  MultiParamTypeClasses
  MultiWayIf
  NamedFieldPuns
  OverloadedStrings
  PatternSynonyms
  RankNTypes
  ScopedTypeVariables
  StandaloneDeriving
  TupleSections
  TypeApplications
  TypeFamilies
  TypeFamilyDependencies
  TypeOperators
